coverage:
  # See http://docs.codecov.io/docs/ignoring-paths
  ignore:
    # compiled output
    - 'lib/'
    # dependencies
    - '**/node_modules'
    # IDEs and editors
    - '.vscode'
    # other (more specific)
     - 'bin'
     - 'messages'