environment:
  nodejs_version: '10'

cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

# version format
version: '{branch}-{build}'

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Limit the number of last commits when cloning the repo/branch
clone_depth: 1

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Build on x64 only
platform: x64

install:
  - ps: Install-Product node $env:nodejs_version x64
  - appveyor-retry yarn install

# disable appveyor's MSBuild mode.
build: off

build_script:
  - ps: Write-Host “Prepack FLS plugin”
  - yarn run prepack

test_script:
  - node --version
  - yarn --version
  - yarn test
