name: create-git-tag
runs:
  using: composite
  steps:
  - uses: "./.github/actions/gh-config"
  - name: Create new git tag
    run: |-
      PKG_TAG="v$(cat package.json | jq -r .version)"
      git tag -a $PKG_TAG -m "Releasing ${PKG_TAG}"
      git push origin $PKG_TAG
    shell: bash