name: gitConfig
description: "Sets git username/email and push behavior"

runs:
  using: composite
  steps:
    - run: git config --global user.email ${{ secrets.SF_IDEE_BOT_GITHUB_TOKEN }}
      shell: bash
    - run: git config user.name 'Release Bot'
      shell: bash