name: ssh-config
runs:
  using: composite
  steps:
  # Ensure parameter if_key_exists is set correctly
  - name: Install SSH key
    uses: shimataro/ssh-key-action@v2
    with:
      key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
      name: circle_ci_id_rsa
      known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
      if_key_exists: fail
  - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    shell: bash