name: setup-publish
runs:
  using: composite
  steps:
  - uses: "./.github/actions/gh-config"
  - uses: actions/checkout@v2
  - name: restore_cache
    uses: actions/cache@v2
    with:
      key: v2-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      restore-keys: |-
        v2-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
        v2-npm-{{checksum ".circleci/config.yml"}}
  - name: Install dependencies
    run: |-
      yarn --version
      node --version
      yarn
    shell: bash
  - name: Bump package version
    run: |-
      npx lerna version << pipeline.parameters.publish-type >> --force-publish --no-git-tag-version --exact --yes
      git add .
      export RELEASE_TAG="$(node -pe "require('./lerna.json').version")"
      git commit --allow-empty -m "chore: updated version $RELEASE_TAG [ci skip]"
    shell: bash
  - name: Build project
    run: yarn build
    shell: bash
  - name: Generate plugin manifest
    run: yarn manifest:generate
    shell: bash
  - name: Pack Library
    run: npm pack
    working-directory: "./packages/templates"
    shell: bash