name: version, tag and github release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'
      - run: yarn
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@d360fad3a42feca6462f72c97c165d60a02d4bf2
        with:
          git-user-name: Release Bot
          git-user-email: ${{ secrets.GH_EMAIL }}
          github-token: ${{ secrets.SF_IDEE_BOT_GITHUB_TOKEN }}
          skip-version-file: true
          output-file: false
          tag-prefix: ""
          pre-commit: ./scripts/bump-lerna-version.js
          fallback-version: 55.2.0
      - name: Create Github Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.SF_IDEE_BOT_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}