name: publish plugin

on:
  workflow_call:
    inputs:
      tag:
        description: tag that needs to be published
        type: string
        required: true
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to be published
        type: string
        required: true

jobs:
  publish:
    defaults:
      run:
        working-directory: "~/cli/packages/plugin-templates"
    runs-on: ubuntu-latest
    container:
      image: node:14
    steps:
    - name: CLI NPM Publish
      uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@main
      with:
        ctc: true
        sign: true
        githubTag: ${{ inputs.tag }}
        secrets: inherit