name: publish templates-bundle
on:
  workflow_run:
    workflows:
      - Version, Tag and Github Release
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'

jobs:
  call-release-workflow:
    if: ${{ inputs.branch || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')}}
    uses: forcedotcom/bundle-publish-scripts/.github/workflows/releaseWithCoreBundle.yml@main
    secrets: inherit
    with:
      branch: ${{ inputs.branch || 'main'}}
