name: publish templates-bundle
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'

jobs:
  call-release-workflow:
    uses: forcedotcom/bundle-publish-scripts/.github/workflows/releaseWithCoreBundle.yml@main
    with:
      branch: ${{ inputs.branch }}
