name: test

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
        shell: bash
      - uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
