name: Tests

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  linux-unit-tests:
    uses: ./.github/workflows/unitTestsLinux.yml
  windows-unit-tests:
    uses: ./.github/workflows/unitTestsWindows.yml
  xNuts:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/externalNut.yml@main
    strategy:
      fail-fast: false
    with:
      packageName: '@salesforce/templates'
      externalProjectGitUrl: 'https://github.com/salesforcecli/plugin-templates'
      os: 'ubuntu-latest'
      useCache: false
    secrets: inherit
