name: test

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  git-config:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
        shell: bash
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
